### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by ecordani** [robsonvn/laravel-couchdb#10]
Hi,
I've created a new Laravel 5.5 project but when I try to use, for example, the all() method:
`$categories = Category::all();`
I get this exception:
**Exception with message 'QueryException No index matches the index specified with "use_index"'**
I'm able to create new documents, so the configuration in .env file is correct.
Thanks

**Comment by ecordani** [comment]
Tested also with Laravel 5.4.30, same exception.

**Comment by robsonvn** [comment]
Hi,

This issue is related to the new version 2.1.1 of Couch DB released last month, they changed a response code. I'm working in a new version that supports all 2.1.1 features but I'm gonna release a hot fix for it today.

The library still not 100% function on Laravel 5.5 so I recommend 5.4.x, sorry.

**Comment by robsonvn** [comment]
@ecordani I have just release the hotfix (2.0.2), could you check it out ?

**Comment by ecordani** [comment]
Hi Rob,
thank you very much, now it works perfectly! I'll stay with 5.4 and I'll look forward for updates for 5.5. Btw your package is simply amazing, we are working with CouchDB for our next gen platform for our iOS applications and it's a huge time saver.

**Comment by robsonvn** [comment]
You're welcome! Now I'm back from holidays will start wok on this new release. Cheers.
