### ISSUE TITLE
QueryBuilder with Relations

### ISSUE THREAD

**Issue by edukmattos** [robsonvn/laravel-couchdb#16]
I have various documents separeted by field "type" with the relations:

Regions.php

namespace App\Entities;

use Robsonvn\CouchDB\Eloquent\Model as Eloquent;
use Robsonvn\CouchDB\Eloquent\SoftDeletes;

class Region extends Eloquent
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $collection = 'regions';       
    protected $fillable = [
    	'code',
    	'description'
    ];

    public function cities()
    {
        return $this->hasMany('App\Entities\City');   
    }
--------------------------------------------------------------------------------------------------------
City
namespace App\Entities;

use Robsonvn\CouchDB\Eloquent\Model as Eloquent;
use Robsonvn\CouchDB\Eloquent\SoftDeletes;

class City extends Eloquent
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    protected $collection = 'cities';
       
    protected $fillable = [
    	'state_id',
    	'description',
        'region_id'
    ];
    public function region()
    {
        return $this->belongsTo('App\Entities\Region'); 
    }
----------------------------------------------------------------------------------------------------------
Partner
namespace App\Entities;

use Robsonvn\CouchDB\Eloquent\Model as Eloquent;
use Robsonvn\CouchDB\Eloquent\SoftDeletes;

class Partner extends Eloquent
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    protected $collection = 'partners';

    protected $fillable = [
        'name',
        'partner_sector_id',
        'address',
        'zip_code',
        'neighborhood',
        'phone',
        'mobile',
        'email', 
        'city_id',
        'partner_type_id'
    ];
  
    public function city()
    {
        return $this->belongsTo('App\Entities\City'); 
    }
------------------------------------------------------------------------------------------------------------------------------
I need to perform a search and should return all the resident partners in the cities belonging to the informed region.

Below, my code but is not working.

return $this->partner
 ->select('partners.*')
 ->join('regions', 'cities.region_id', '=', 'regions.id')
 ->join('cities', 'partners.city_id', '=', 'cities.id')
 ->where('cities.region_id','=',$srch_partner_region_id);
 ->get(); 

Where is my error ?

**Comment by diegonella** [comment]
Do you have use eager / lazy loading for relations
$p = \App\Partner::with(['city'])->get();

**Comment by edukmattos** [comment]
Hi, @diegonella !
Thanks for your help but didnt work !
When i use with MySql database, work it.
I think my problem error is with this package laravel-couchdb and not with Laravel.

**Comment by robsonvn** [comment]
Hi @ecmattos you must remember that CouchDB is a no relational database.

Although this library support Relationship, it does not do joint queries because Mango Query does not do joins (where is a CouchDB limitation). 

Relationships are for eager/lazy loading and to ease updates/deletions.

In your case for instance, when you want to retrieve the region of a given city you might do something like:

```php
$sao_paulo = \App\City::where('name', '=', 'Sao Paulo')->first();
$sao_paulo->region->name;
```

But when you want to search all cities related to a given Region, you might have to do separate queries:

```php
$southeast = \App\Region::where('name', '=', 'Southeast')->first();
$cities = \App\City::where('region_id', '=', $southeast->_id)->get();

```
Which lead us to our last step: Retrieve all the partners from a given region:

```php
$partners = \App\Partner::whereIn('city_id', [$cities->pluck('_id')])->get();
```

Since this library is built on top of Laravel Eloquent, you can always fall back to the Eloquent Documentation to learn how to use Model methods such as "where", "whereIn" and Collection methods such as "pluck"

**Comment by edukmattos** [comment]
Tks for help !
I got it !
